import React, { useState } from 'react';
import { useData } from '../contexts/DataContext';
import { FileText, Plus, Download, ChevronRight, Loader2, CheckSquare, Square, Sparkles } from 'lucide-react';

export const Dossiers: React.FC<{ onNavigate: (page: string) => void }> = ({ onNavigate }) => {
  const { evidence, dossiers, createDossier, autoGenerateDossier, isAnalyzing } = useData();
  const [isCreating, setIsCreating] = useState(false);
  const [selectedEvidence, setSelectedEvidence] = useState<string[]>([]);
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');

  const toggleSelection = (id: string) => {
    setSelectedEvidence(prev => 
      prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]
    );
  };

  const handleCreate = async () => {
    if (!title || selectedEvidence.length === 0) return;
    await createDossier(title, description, selectedEvidence);
    setIsCreating(false);
    setTitle('');
    setDescription('');
    setSelectedEvidence([]);
  };

  if (isCreating) {
    return (
      <div className="max-w-4xl mx-auto">
        <header className="mb-6 flex justify-between items-center">
            <h1 className="text-2xl font-bold text-slate-900">New Dossier</h1>
            <button onClick={() => setIsCreating(false)} className="text-slate-500 hover:text-slate-800">Cancel</button>
        </header>

        <div className="bg-white p-8 rounded-xl shadow-sm border border-slate-200 space-y-8">
            <div className="space-y-4">
                <div>
                    <label className="block text-sm font-semibold text-slate-700 mb-1">Dossier Title</label>
                    <input 
                        type="text" 
                        value={title}
                        onChange={e => setTitle(e.target.value)}
                        placeholder="e.g. Harassment Campaign Jan 2024"
                        className="w-full p-3 border border-slate-300 rounded-lg bg-slate-50"
                    />
                </div>
                <div>
                    <label className="block text-sm font-semibold text-slate-700 mb-1">Description / Context</label>
                    <textarea 
                        value={description}
                        onChange={e => setDescription(e.target.value)}
                        placeholder="Briefly describe the context for this collection of evidence..."
                        className="w-full p-3 border border-slate-300 rounded-lg bg-slate-50 h-24 resize-none"
                    />
                </div>
            </div>

            <div>
                <h3 className="text-lg font-bold text-slate-900 mb-4">Select Evidence Items ({selectedEvidence.length})</h3>
                <div className="border border-slate-200 rounded-lg overflow-hidden max-h-96 overflow-y-auto">
                    {evidence.length === 0 && <div className="p-4 text-center text-slate-500">No evidence available.</div>}
                    {evidence.map(item => (
                        <div 
                            key={item.id} 
                            onClick={() => toggleSelection(item.id)}
                            className={`p-4 border-b border-slate-100 cursor-pointer flex items-start gap-4 hover:bg-slate-50 ${selectedEvidence.includes(item.id) ? 'bg-blue-50/50' : ''}`}
                        >
                            <div className={`mt-1 ${selectedEvidence.includes(item.id) ? 'text-brand-600' : 'text-slate-300'}`}>
                                {selectedEvidence.includes(item.id) ? <CheckSquare /> : <Square />}
                            </div>
                            <div className="flex-1">
                                <div className="flex justify-between mb-1">
                                    <span className="font-semibold text-sm capitalize text-slate-700">{item.platform}</span>
                                    <span className="text-xs text-slate-500">{new Date(item.timestamp).toLocaleDateString()}</span>
                                </div>
                                <p className="text-sm text-slate-600 line-clamp-2 font-mono bg-white/50 p-1 rounded">{item.content}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            <div className="flex justify-end gap-3 pt-4 border-t border-slate-100">
                <button onClick={() => setIsCreating(false)} className="px-6 py-2 text-slate-600 font-medium hover:bg-slate-50 rounded-lg">Cancel</button>
                <button 
                    onClick={handleCreate}
                    disabled={selectedEvidence.length === 0 || !title || isAnalyzing}
                    className="px-6 py-2 bg-brand-600 text-white font-bold rounded-lg hover:bg-brand-700 disabled:opacity-50 flex items-center gap-2"
                >
                    {isAnalyzing ? <><Loader2 className="animate-spin" /> Generating Summary...</> : 'Generate Dossier'}
                </button>
            </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
            <h1 className="text-3xl font-bold text-slate-900">My Dossiers</h1>
            <p className="text-slate-500 mt-2">Organize evidence into secure, shareable packages.</p>
        </div>
        <div className="flex gap-3">
             <button 
                onClick={autoGenerateDossier}
                disabled={isAnalyzing || evidence.length === 0}
                className="px-6 py-3 bg-indigo-600 text-white font-bold rounded-lg shadow hover:bg-indigo-700 flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                title="Automatically groups all available evidence into a new dossier with AI-generated title and summary."
            >
                {isAnalyzing ? <Loader2 className="animate-spin" size={20} /> : <Sparkles size={20} />}
                <span>Auto-Generate</span>
            </button>
            <button 
                onClick={() => setIsCreating(true)}
                className="px-6 py-3 bg-white border border-slate-300 text-slate-700 font-bold rounded-lg hover:bg-slate-50 flex items-center gap-2"
            >
                <Plus size={20} /> New Custom Dossier
            </button>
        </div>
      </header>

      {dossiers.length === 0 ? (
          <div className="text-center py-16 bg-white rounded-xl border border-dashed border-slate-300">
              <FileText size={48} className="mx-auto text-slate-300 mb-4" />
              <h3 className="text-lg font-medium text-slate-900">No dossiers yet</h3>
              <p className="text-slate-500 mb-6">Create a dossier to bundle evidence for lawyers or authorities.</p>
              <div className="flex justify-center gap-4">
                 <button onClick={autoGenerateDossier} disabled={evidence.length === 0} className="text-indigo-600 font-bold hover:underline flex items-center gap-1">
                    <Sparkles size={16} /> Auto-Generate from {evidence.length} items
                 </button>
                 <span className="text-slate-300">|</span>
                 <button onClick={() => setIsCreating(true)} className="text-brand-600 font-bold hover:underline">
                    Create Manually
                 </button>
              </div>
          </div>
      ) : (
          <div className="grid gap-6">
              {dossiers.map(dossier => (
                  <div key={dossier.id} className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
                      <div className="flex justify-between items-start mb-4">
                          <div>
                              <h3 className="text-xl font-bold text-slate-900">{dossier.title}</h3>
                              <p className="text-sm text-slate-500">Generated {new Date(dossier.generatedAt).toLocaleDateString()} · {dossier.items.length} Items</p>
                          </div>
                          <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase ${dossier.severity === 'Critical' ? 'bg-red-100 text-red-800' : 'bg-orange-100 text-orange-800'}`}>
                              {dossier.severity} Severity
                          </span>
                      </div>
                      
                      <div className="mb-4">
                          <p className="text-slate-600 italic text-sm">{dossier.description}</p>
                      </div>

                      {dossier.aiSummary && (
                          <div className="bg-slate-50 p-4 rounded-lg mb-6 border-l-4 border-brand-300">
                              <p className="text-xs font-bold text-slate-400 uppercase mb-2 flex items-center gap-1"><Sparkles size={10} /> Executive Summary (AI)</p>
                              <p className="text-slate-700 text-sm leading-relaxed">{dossier.aiSummary}</p>
                          </div>
                      )}

                      <div className="flex gap-4 border-t border-slate-100 pt-4">
                          <button className="flex-1 flex items-center justify-center gap-2 px-4 py-2 border border-slate-300 rounded-lg text-slate-700 font-bold hover:bg-slate-50">
                              <Download size={18} /> Download PDF
                          </button>
                          <button className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-lg font-bold hover:bg-slate-800">
                              Share Securely <ChevronRight size={18} />
                          </button>
                      </div>
                  </div>
              ))}
          </div>
      )}
    </div>
  );
};